let actionTypes = {
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_ERROR: "AUTH_LOGIN_ERROR",
  GOOGLE_LOGIN_SUCCESS: "AUTH_GOOGLE_LOGIN_ERROR",
  GOOGLE_LOGIN_ERROR: "AUTH_GOOGLE_LOGIN_ERROR",
  SHOW_AUTH_MODAL: "SHOW_AUTH_MODAL",
  HIDE_AUTH_MODAL: "HIDE_AUTH_MODAL",
};
export default actionTypes;
